### ISSUE TITLE
Failed to activate the hyperclick-latex package

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#3]
I updated hyperclick-latex and got the following error 

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [hyperclick-latex](https://github.com/Aerijo/hyperclick-latex) package 0.1.1

### Stack Trace

Failed to activate the hyperclick-latex package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/hyperclick-latex/lib/latex-provider.js:4:11)
    at /packages/hyperclick-latex/lib/latex-provider.js:261:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/hyperclick-latex/lib/hyperclick-latex.js:2:18)
    at /packages/hyperclick-latex/lib/hyperclick-latex.js:20:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:244:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-latex 0.8.0 
autocomplete-latex-cite 0.3.1 
autocomplete-latex-references 0.3.1 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.16 
grammar-token-limit 0.1.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-latex 0.1.1 
intentions 1.1.5 
language-cmake 1.1.0 
language-latex 1.1.1 
latex 0.49.0 
linter 2.2.0 
linter-spell 0.15.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
pigments 0.40.2 
project-manager 3.3.5 
todo-show 2.1.0 
```

**Comment by Aerijo** [comment]
My bad, I forgot to add that module to the list of dependencies. The patch should fix it.

**Comment by PierreMarchand20** [comment]
It works great
